AvsForm2.h: avoid conflicts with XawForm.h
Gets rid of a bunch of redeclaration errors from gcc 14, such as:

../../xts5/include/AvsForm2.h:137:5: error: redeclaration of enumerator
 ‘XawChainTop’
  137 |     XawChainTop,                /* Keep this edge a constant distance from
      |     ^~~~~~~~~~~
In file included from XtGetConstraintResourceList.c:48:
/usr/include/X11/Xaw/Form.h:108:5: note: previous definition of
 ‘XawChainTop’ with type ‘enum <anonymous>’
  108 |     XawChainTop,                /* Keep this edge a constant distance from
      |     ^~~~~~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/test/xts/-/merge_requests/10>