ShowRep.c: Add missing % to printf-style format string
Fixes warning from gcc-14 after adding printf attributes to Log_* calls:

XstlibInt.h:207:44: warning: too many arguments for format [-Wformat-extra-args]
  207 | #define BPRINTF2(fmt,var)       Log_Debug2((fmt),(var));
      |                                            ^~~~~
ShowRep.c:187:17: note: in expansion of macro ‘BPRINTF2’
  187 |                 BPRINTF2("\tdoNotPropagateMask = 0x08x\n",((xGetWindowAttributesReply *)mp)->doNotPropagateMask);
      |                 ^~~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/test/xts/-/merge_requests/10>