Fix -Wint-conversion errors in generated code in test cases
Cast XCALL to (void) so that mc doesn't generate code to store the
result in an "int" variable, resulting in:

XSetAfterFunction.c:200:21: error: assignment to ‘int’ from
 ‘int (*)(Display *)’ {aka ‘int (*)(struct _XDisplay *)’}
 makes integer from pointer without a cast [-Wint-conversion]
  200 |         ValueReturn = XSetAfterFunction(display, procedure);
      |                     ^

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/test/xts/-/merge_requests/10>