Rcv_Ext_Evt: add missing argument to unpack2() call
Fixes compiler error now that we have a function prototype for it:

RcvExtEvt.c:253:45: error: too few arguments to function ‘unpack2’
  253 |                         rpi->device_state = unpack2(&rbp);
      |                                             ^~~~~~~
In file included from RcvExtEvt.c:140:
XstlibInt.h:159:16: note: declared here
  159 | unsigned short unpack2(void *bufpp, int swap);
      |                ^~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/test/xts/-/merge_requests/10>