Rcv_Ext_Evt: drop unused argument "base"
Fixes compiler error now that we have a function prototype for it:

RcvEvt.c:166:13: error: too few arguments to function ‘Rcv_Ext_Evt’
  166 |             Rcv_Ext_Evt(rp,rbuf,client);
      |             ^~~~~~~~~~~
In file included from RcvEvt.c:132:
XstlibInt.h:325:5: note: declared here
  325 | int Rcv_Ext_Evt (xEvent *rp, char rbuf[], int client, int base);
      |     ^~~~~~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/test/xts/-/merge_requests/10>